# Generated by Django 3.0.5 on 2020-08-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='姓名')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('mail', models.CharField(blank=True, max_length=64, verbose_name='邮箱')),
            ],
        ),
    ]
