# Generated by Django 2.2.5 on 2020-08-12 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='UDRight',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
