# Generated by Django 2.2.5 on 2020-08-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0002_auto_20200812_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='姓名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
            ],
        ),
    ]
