# Generated by Django 3.0.5 on 2020-08-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail_address',
            field=models.CharField(default='1@qq.com', max_length=64, verbose_name='邮箱'),
            preserve_default=False,
        ),
    ]
